guardian/ssm-scala

- README.md
- build.sbt
Also now uses semantic versioning to match the release tag
> Add documentation for first release

- src/main/scala/com/gu/ssm/SSH.scala
Comes back to default colour instead of hard coded black, after red, during ssm command
> Comes back to default colour instead of hard coded black, after red.

- build.sbt
To match the current release tag.
> Update version in build.sbt

- README.md
- src/main/scala/com/gu/ssm/ArgumentParser.scala
- src/main/scala/com/gu/ssm/Main.scala
- src/main/scala/com/gu/ssm/SSH.scala
- src/main/scala/com/gu/ssm/models.scala
- src/test/scala/com/gu/ssm/SSHTest.scala
**Example**
```
$ ssm ssh -i i-066ea79153a164de8 --profile ophan --private --user hadoop
```
> Add support for specifying ssh user

- README.md
- src/main/scala/com/gu/ssm/Logic.scala
- src/main/scala/com/gu/ssm/Main.scala
- src/main/scala/com/gu/ssm/aws/EC2.scala
- src/main/scala/com/gu/ssm/models.scala
- src/test/scala/com/gu/ssm/LogicTest.scala
- src/test/scala/com/gu/ssm/SSHTest.scala
Preferentially uses public dns if the instance has one
Integrates better with users' ssh configurations.
No
> Support domain names

- src/main/scala/com/gu/ssm/ArgumentParser.scala
Correcting incorrectly positioned cli help texts
> Correction in cli help text

- src/main/scala/com/gu/ssm/Main.scala
- src/main/scala/com/gu/ssm/SSH.scala
- src/main/scala/com/gu/ssm/utils/KeyMaker.scala
- src/test/scala/com/gu/ssm/SSHTest.scala
Few renamings to add clarity (preliminary work of coming PR).
> Adding clarify in variable and function names

- README.md
Add missing `brew upgrade ssm`
> Update README with upgrade instructions

- README.md
This change advertises a better cloud-formation update for enabling SSM.
> Update README with better cloudformation instructions

- README.md
- generate-executable-prefix
- src/main/scala/com/gu/ssm/ArgumentParser.scala
- src/main/scala/com/gu/ssm/aws/AwsAsyncHandler.scala
Permits immediate execution of the ssh command so that the entire process is a single command.
Simpler interface for users.
> Add -x or --execute option to immediately execute

- README.md
- build.sbt
Correct the version number and  update release checklist.
> Fix version number discrepancy

- build.sbt
Bumps version ready for homebrew release.
> Bump version for release of --execute

- README.md
> Add documentation for 'Too many authentication failures'

- build.sbt
> Upgrade ch.qos.logback to version 1.2.3

- src/main/resources/logback.xml
Solves: https://github.com/guardian/ssm-scala/issues/92
> Move the log file to the user's home directory

- README.md
Update the readme for first time (ssh) users.
> SSH real quick for the impatient first time user

- .github/workflows/compile-test.yml
Adds a workflow to run `sbt test`. 
This should reduce the risk of merging broken code as we'll get a red cross on the PR (to go with the semi permanent snyk ❌ ...)
> Add github actions workflow to compile and test

- .github/CONTRIBUTING.md
Change reference to say "main" in contributing.md
> update master to main

- build.sbt
Bumps to 2.4.0, which includes #245.
> Version 2.4.0

- .github/workflows/compile-test.yml
Updates java in the `compile-test` action from v8 -> v21.
> feat: use java 21

- build.sbt
Bumps the version ahead of the next release. We'll create the new tag (and release binary) off the result of merging this PR.
> Bump version for next release

- build.sbt
- generate-executable.sh
Seems to work ok, tested locally by SSHing into an instance.
> update to latest scala LTS 3.6.2

- build.sbt
For future viewers, this is following the [instructions in Readme](https://github.com/guardian/ssm-scala?tab=readme-ov-file#release-a-new-version).
To do:
> prepare release 3.8.1

- README.md
Just slightly easier to follow, having recently done a release.
> docs: Update readme to clarify release steps
