README.md
1. Update the command syntax with placeholder markers.
2. Correct an instance id.
=> Corrections in README

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/IO.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/aws/AwsAsyncHandler.scala, src/main/scala/com/gu/ssm/aws/EC2.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/LogicTest.scala, src/test/scala/com/gu/ssm/SSHTest.scala
`ssm ssh -t app,stack,stage --profile awsprofile`
`ssm repl -t app,stack,stage --profile awsprofile`
`ssm cmd -c ls -t app,stack,stage --profile awsprofile`
Separate UI with placeholder output when running the ssh command
convert any cmd file from within the argParser, and just pass a string around from then on
the strict requirements on commands and some opts (profile) now make them unnecessary
Update the tests, delete unneeded methods, spelling, formatting, etc.
=> Convert option parsing to use commands for the three major choices

src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/MainTest.scala, src/test/scala/com/gu/ssm/SSHTest.scala
With this change while running
```
$ java -jar ./ssm.jar cmd -c ls --profile security --instances i-011a0282bac767f41,i-09d626a5abdfb5c74,i-123456
```
where only the fist instance id (`i-011a0282bac767f41`) is correct, the output now becomes
```
The following instance(s) could not be found: i-09d626a5abdfb5c74, i-123456
========= i-011a0282bac767f41 =========
STDOUT:
amazon-ssm-agent.deb
bin
(...)
vmlinuz
STDERR:
```
=> UI Improvment: reporting erroneous instance ids while using cmd

src/main/scala/com/gu/ssm/Interactive.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/MainTest.scala
We now report in the repl screen that some instances could not be found. 
This is the sister PR of: https://github.com/guardian/ssm-scala/pull/13
Running 
```
$ java -jar ./ssm.jar repl --profile security --instances i-04d908c9a645cd264,i-123456
```
where the only valid id is `i-04d908c9a645cd264`, we get
The following screenshot shows the error message shown after the command having been ran ( `i-049447ce9628d26fe` was correct instance id and `i-123456` an incorrect one )
This change contains few function signatures changes to carry `executionTarget` where it wasn't originally available.
=> UI Improvment: reporting erroneous instance ids while using repl

README.md, generate-executable-prefix, generate-executable.sh
This change introduces `generate-executable.sh` which can now be used to generate single executable called `ssm`. The documentation has been updated accordingly.
=> Simplify use by providing an executable

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/IO.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/aws/EC2.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/LogicTest.scala
- Some minor stylistic updates in arguments documentation.
- Added a new (optional) command line argument in the case of the ssh command.
- Updated the code to process this extra argument.
The net result is that users can now specify that they want ssh to proceed with one single instance if more than one instances where found. (Request from the CAPI team).
```
$ ./ssm ssh -p security -t security-hq,security,PROD
Error choosing single instance, found i-09bab0e2ecef2b184, i-0792c00571352d0e4
$ ./ssm ssh -p security -t security-hq,security,PROD -a true
========= i-09bab0e2ecef2b184 =========
STDOUT:
ssh -i /private/var/folders/7b/djwwh2kd4m95smw88z4hvfnr0000gn/T/security_ssm-scala_temporary-rsa-private-key4611386747952826521.tmp ubuntu@34.245.57.216;
```
- Updated the README with the …
=> New (optional) command line argument in the case of the ssh command: -a, --any <boolean>

src/main/scala/com/gu/ssm/IO.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/test/scala/com/gu/ssm/LogicTest.scala
This change renames `getRelevantInstance` into `getSSHInstance`, modifies its internal logic to handle the case of `Instance`s without an IP address and updates the tests.
=> getRelevantInstance -> getSSHInstance

src/test/scala/com/gu/ssm/SSHTest.scala
@adam
Follow up of the office discussion about:
```
LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant()
```
java.util.Date doesn't have a time zone attached to it. In fact AWS is not making any choice of a "default time zone" when they return it in their SDK, because java.util.Date is essentially just a Long.
The problem we have is "create an Instant", not "create a datetime in UTC time zone".
So now that we don't have to worry about timezones, what is the most perfect way to create an Instant ?
This change does it perfectly (^_^)
=> Instant.now()

src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/models.scala
We were finding the following error when running a command against all instances of our elasticsearch cluster:
```
$  ~ ./ssm cmd -c 'date' --profile ophan -t elasticsearch,ophan,PROD
SLF4J: A number (14) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
Unknown error while making an API call to AWS' AWSSimpleSystemsManagement service, null (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: InvocationDoesNotExist; Request ID: d46022a8-188f-11e8-9548-511ec617bfed)
```
We fix this by capturing this particular error from AWS as a new `CommandStatus`: `InvocationDoesNotExist`.
We have tested …
=> Introduce InvocationDoesNotExist and handle AWS error

README.md, src/main/scala/com/gu/ssm/aws/SSM.scala
We can take advantage of the strongly-typed `InvocationDoesNotExistException` provided by the AWS SDK. This doesn't make the fix introduced with d9d691e in #34 any better, just a bit more concise, and more strongly-typed!
=> Detect `InvocationDoesNotExistException` by type rather than message text

README.md
Update the README with a new installation procedure using `brew` and two tasks to sync the latest version with the Guardian tap.
Thanks @sihil for the idea and work.
=> New installation procedures and developer release notes

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds contributing guidelines and issue/PR templates similar to those found in other Guardian repositories
- More detail in issues and PRs
- Makes it easier for people outside the team or The Guardian to contribute
Potentially, some of the notes on developing/contributing that are currently in the README could be moved to CONTRIBUTING.md
YMMV 😁
=> Add templates for PRs and issues, and contributing guidelines

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/SSHTest.scala
This change introduces the `--raw` flag for the ssh subcommand allowing the output to be used as part of a pipe. For instance
```
ssm ssh --profile security -t security-hq,security,PROD --newest --raw | bash
```
will execute the ssh connection directly. 
Note that we moved from 
```
sshOutput(result: (InstanceId, String))
``` 
to
```
sshOutput(machineOutput: Boolean)(result: (InstanceId, String))
``` 
as the best way to keep `setUpSSH`'s `programResult.fold` clean.
=> Introduces --raw

src/main/scala/com/gu/ssm/SSH.scala, src/test/scala/com/gu/ssm/SSHTest.scala
Forces pseudo terminal allocation for --raw invocation
--raw is usually piped to bash, which requires a pseudo terminal to be forced
No
=> Handle pseudo-terminal for raw

src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/test/scala/com/gu/ssm/SSHTest.scala
Posix compliance - does not rely on root having a bash shell by default
Will work on machines which do not use bash for root.
Also introduces a one second delay before output in "--raw | bash" mode, which should prevent the race condition between adding the key and invoking the command in bash.
=> Remove bashisms

README.md, src/main/scala/com/gu/ssm/Main.scala
This change removes the assumption that bastions always have a public IP address, and update the documentation accordingly.
=> Clarifying the use of --private for bastions

README.md, build.sbt
Rebump version to 0.9.1 prior to release for homebrew.
Release including --execute without marking as v1
=> Unbump version pending further work to support Discussion team

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/SSHTest.scala
There's been occurences of bastions connections strings of the form
```
ssh -A -i /path/to/temp/private/key -t -t ubuntu@bastion-hostname \
-t -t ssh -t -t ubuntu@target-ip-address;
```
not working, because the private file was not found for the second ssh connection, leading to a "Permission denied (publickey)" error message.
When this happens the user can use the `-a`, `--agent` flag that performs a registration of the private key at the local ssh agent. With this flag, ssm command
```
ssm ssh --profile <account-name> --bastion <instanceId1> \
-i <instanceId2> --agent
```
returns
```
ssh-add /path/to/temp/private/key && \
ssh -A ubuntu@bastion-hostname \
-t -t ssh ubuntu@target-ip-address;
```
=> Introduces the -a, --agent flags

build.sbt, src/main/scala/com/gu/ssm/SSH.scala, src/test/scala/com/gu/ssm/SSHTest.scala
This change adds the option -t <number> to the ssh-add command in the bastion connection --agent case. Also version 0.9.3.
=> Limit agent registration time to prevent "Received disconnect (...) Too many authentication failures" error

README.md
README update: Explanation of the use of the wording "tainted" in the target instance's welcome message.
=> 'Tainted' Instances

src/main/scala/com/gu/ssm/SSH.scala, src/test/scala/com/gu/ssm/SSHTest.scala
On some instances authorized_keys comes owned by root. This change ensures that the file is owned by ubuntu or the default user provided by the user.
=> Ensure correct ownership of the authorized_keys file on target

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala
Turn on ssh-agent usage by default if a bastion is used.
Permit explicitly turning off ssh-agent.
People using bastions will almost always want to use ssh-agent.
=> Make agent default with bastions

README.md, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/test/scala/com/gu/ssm/LogicTest.scala
When the `--private` flag is used, we use instances private IPs. If not, we default to the public IP when available and otherwise use the private IP.
Little detail: moving from
```
def getSSHInstance(instances: List[Instance], sism: SingleInstanceSelectionMode, usePrivate: Boolean): Either[FailedAttempt, Instance]
```
to 
```
def getSSHInstance(instances: List[Instance], sism: SingleInstanceSelectionMode): Either[FailedAttempt, Instance]
```
simplified the tests.
Simpler user interface.
=> Unless --private, use public IP when available and otherwise private IP

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala
My recent changes to SSM in #84 made liberal use of quotes when specifying options (particularly around `ProxyCommand` for bastion access). This breaks `--raw` if you execute it directly as bash will interpret `ssh -o "IdentitiesOnly yes"` as four separate terms: `ssh`, `-o`, `"IdentitiesOnly` and `yes"`. By using `eval` it ensures that it is evaluated as if it had been typed into a terminal directly.
This is therefore a documentation change that advises people to use eval in combination with `--raw`
People were getting an error when using `--raw`. This documents how it can be used.
No
=> Improve the documentation for the --raw option

src/main/scala/com/gu/ssm/SSH.scala
The temporary files generated by ssm are not automatically cleaned up, so we are moving them to the OS's temp folder.
=> Moving user's temporary files to OS's temp folder

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/SSHTest.scala
This PR adds the **scp** sub command to **ssm**, for performing secure copy.
**ssm** support the **scp** sub command for the secure transfer of files and directories.
An example of usage is 
```
./ssm scp -p account -t app,stack,stage /path/to/file1 :/path/to/file1
``` 
Which outputs
```
scp -i /path/to/identity/file.tmp /path/to/file1 ubuntu@34.242.32.40:/path/to/file2;
```
Otherwise 
```
./ssm scp -p account -t app,stack,stage :/path/to/file1 /path/to/file2
```
outputs 
```
scp -i /path/to/identity/file.tmp ubuntu@34.242.32.40:/path/to/file1 /path/to/file2 ;
```
For the moment we only support moving files. Support for directories will come in the next PR.
=> Introduce new sub command 'scp' for secure copy

src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/aws/AwsAsyncHandler.scala, src/main/scala/com/gu/ssm/models.scala, src/main/scala/com/gu/ssm/utils/attempt/Attempt.scala, src/main/scala/com/gu/ssm/utils/attempt/Failure.scala, src/test/scala/com/gu/ssm/SSHTest.scala
This replaces the string output type with various output types that can be processed by the UI classes. By allowing this to be returned by the actual methods we grant much greater flexibility in how output is presented (and can be optionally presented using the new `--verbose` flag).
=> Move IO right to the edge, allow flexible output and add --verbose flag

README.md
AmazonEC2RoleforSSM is way too permissive and it's not immediately clear of the extent to which this is the case, so very easy for a developer to use it.
Removes the suggestion to use AmazonEC2RoleforSSM
AmazonEC2RoleforSSM is a very permissive policy that can easily expose access to s3 every bucket unnecessarily.
=> Remove suggestion to use AmazonEC2RoleforSSM

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/models.scala
**EDIT** I spoke to Simon and now it's loads better
Fixes SSM's ssh for connecting to instances running Ubuntu 18.04.
Bug fix! At the moment SSM is unusable for instances that use Ubuntu Bionic (18.04) as their base image.
We now query `sshd` directly rather than parsing the config files. This is simpler and loads more robust.
=> Fix "output host keys" remote command

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/SSH.scala, src/test/scala/com/gu/ssm/SSHTest.scala
Corrects the problem reported here: https://github.com/guardian/ssm-scala/issues/105
The `-t` option is not actually a `scp` option and its occurrence in the output string of the `scp` subcommands was a vestige of `ssh`.
=> Remove -t options for the scp subcommand

README.md
It is no longer necessary to bake the `ssm-agent` AMIgo role as it is now put into all base images
=> Documentation update to remove unnecessary amigo step

README.md
Corrects raw mode equivalent examples to include ssm prefix which seems to be required.
=> Corrects raw mode equivalent examples

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala
It is sometimes necessary to execute remote bash commands as another user, e.g. when the bash script is in that user's home folder, but also to make sure proper permissions are set on generated files etc.
The `-u` option is already available for `ssm ssh`, applying it to others seems to follow naturally.
=> Add support for -u option in `ssm cmd`

README.md, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/SSHTest.scala
Adds `--ssm-tunnel` flag to [tunnel connections using AWS Systems Manager](https://aws.amazon.com/about-aws/whats-new/2019/07/session-manager-launches-tunneling-support-for-ssh-and-scp/). In practice this means you can access machines without the use of a bastion host and can close port 22 for access entirely, even within the VPC.
This requires the Systems Manager agent to be [at least 2.3.672.0](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html). ~Unfortunately this image is not yet in the Ubuntu base AMI images we use (not even the nightlies as of 19/07/19)~ The image is in the base images we use for AMIgo.
It also requires the instance policies to have additional `ssmmessages` [policy …
=> Optionally tunnel SSH through Systems Manager

src/main/scala/com/gu/ssm/ArgumentParser.scala
Add missing argument to parser so you can tunnel `scp` through SSM (#111)
=> Add `--ssm-tunnel` argument to scp

README.md
Adds a bit more detail to the readme.md, as it wasn't clear from the instructions what would be necessary to make connections over `--ssm-tunnel` once the appropriate permissions were in place.
Hopefully it'll be a little clearer to a reader adding permissions for tunnelling access what's necessary after that's done to successfully connect.
=> Add additional instructions re: `ssm-agent` restart

src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/aws/EC2.scala, src/test/scala/com/gu/ssm/LogicTest.scala
This change follows from https://github.com/guardian/ssm-scala/pull/117 in an eternal quest to make ssh a bit easier. My proposal here is that we allow people to only specify one tag. For example it is now possible to do:
`ssm ssh -x -p deployTools -t grafana`
`ssm ssh -x -p deployTools -t prism,prod --newest`
`ssm ssh -x -p deployTools -t prod,prism --newest`
`ssm ssh -x -p deployTools -t api,code,flexible --newest`
I've also made the describeinstances call even more inefficient by trying to make it less case sensitive, so
`ssm ssh -x -p deployTools -t prism,prod --newest` will actually query:
describeinstances( app=prism|PRISM|prod|PROD, stage=prism|PRISM|prod|PROD)
I've tried to keep order as irrelevant as possible, but without doing multiple API lookups I needed a way to decide which …
=> Allow user to just provide one tag rather than all 3.

README.md, build.sbt, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/models.scala
This modifies ssm-scala so that by default it tries to proxy requests via aws systems manager. This is the preferred approach, as documented in the [readme](https://github.com/guardian/ssm-scala#enabling-ssm-tunnel) as it means you don't have to open up port 22, don't need the VPN, and don't need bastion hosts. Oh my! 
I think enough time has passed since @mbarton 's initial PR https://github.com/guardian/ssm-scala/pull/111 for this to have become mostly standard practice, and this PR will save people having to remember to type `--ssm-tunnel` all the time. 
If ssm tunnel is not desired, the flag `--no-ssm-proxy` will disable this behaviour.
This combined with the work discussed here https://github.com/guardian/ssm-scala/pull/120 will allow you to ssh like this:
`ssm ssh -x -t grafana -p …
=> Make --ssm-tunnel default behaviour.

.editorconfig, README.md
As noted in https://github.com/guardian/domains-platform/pull/52/files#r512522245, update policy document.
This PR also adds a config file for EditorConfig to encourage consistency of intents.
Diff is best seen [w/out whitespace](https://github.com/guardian/ssm-scala/pull/124/files?diff=split&w=1).
=> update policy document

src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/utils/attempt/Attempt.scala, src/test/scala/com/gu/ssm/utils/attempt/AttemptTest.scala
In the investigations account we regularly hit this timeout simply running `ssm ssh`. I think this is because of the time it takes to establish a connection to the SSM agent as subsequent invocations do not time out. When the timeout does occur, ssm hangs rather than exits.
We'd also like to run scripts using `ssm cmd` that will take longer than 25 seconds.
I don't see value in having an arbitrary timeout across the entire program so after this change ssm will wait forever. I may well be missing the reason behind this timeout though.
=> Wait indefinitely

src/main/scala/com/gu/ssm/aws/EC2.scala
This PR excludes non-running instances when running commands against a set of tags. 
This issue was noticed when testing instances were running Wazuh correctly after a deploy. The command was failing with AWS returning `InvalidInstanceId`. Commands run against a specific query ID worked fine. We determine that the commands were being run against the terminated instances due to the deploy.
It should be easier to query recently deployed instances.
I've tested this locally, I'm not sure if there are other ways to test.
=> Filters non-running instances from resolveByTag method

.editorconfig
The global editorconfig declaration was set to 4 spaces, which is at odds with Scala style and the existing codebase. This sets the default to 2 spaces for this project.
Consistent formatting for people with editors configured to obey the editorconfig declaration.
We might consider adding filetype-specific overrides to this configuration (e.g. `xml`, which currently uses 4 spaces in the
project), but my focus is on fixing this for the existing bulk of the program, which is Scala.
=> Scala style is 2 spaces, updates editorconfig accordingly

src/main/scala/com/gu/ssm/Interactive.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/UI.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/LogicTest.scala, src/test/scala/com/gu/ssm/UITest.scala
At the moment, `ssm cmd` will return exit code 0 even if the underlying command has failed.
I'm trying to use it to run a script on a brand new EC2 instance, where the script is downloaded and installed by the launch configuration. If `ssm cmd` runs before the script has been downloaded, the command will result in an error (verified in the SSM web UI) but `ssm cmd` returns a success code.
It's also common to `set -e` in bash scripts to abandon execution on the first failure so the current behaviour can lead to cascading failures in subsequent commands.
This change returns exit code 1 if the command has failed on any of the targets. The stdout returned from the SSM agent will indicate the reason for the failure.
=> Return error code if any invocation fails during ssm cmd

src/main/scala/com/gu/ssm/aws/STS.scala
SSM Scala calls `sts get-caller-identity` to find a username for the SSM command history. Running `ssm cmd` in our VPC was failing with the following error:
```
Unable to execute HTTP request: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/52.94.241.129] failed: connect timed out
```
This is because our VPC does not have outbound internet access as a security measure. We provisioned a VPC endpoint for STS but SSM Scala needs additional configuration to use the regional endpoint rather than the global one.
This change is transparent for local usage by developers.
=> Use regional STS endpoint to work in VPCs without internet access

src/main/scala/com/gu/ssm/aws/AwsAsyncHandler.scala
For example, the error you get if you haven't created a VPC endpoint for STS and don't have outbound internet access:
```
Unable to execute HTTP request: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/52.94.241.129] failed: connect timed out
```
=> Don't hide error messages when we can't determine the service name

src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/aws/AwsAsyncHandler.scala, src/main/scala/com/gu/ssm/aws/EC2.scala, src/main/scala/com/gu/ssm/aws/SSM.scala, src/main/scala/com/gu/ssm/aws/STS.scala, src/main/scala/com/gu/ssm/models.scala
We are automating AMI rotation for our neo4j instance in Giant using a bash script that calls `ssm cmd` to run commands. To run this automatically I'd like to simply run the same script in AWS but unfortunately I get an error:
```
--profile switch or environment variable AWS_PROFILE expected
```
It doesn't help if I `export AWS_PROFILE=default` as AWS credentials are not provided using a file but via the EC2/ECS metadata service:
```
"The config profile (default) could not be found"
```
This PR adds a `--use-default-credentials-provider` flag which we can set if running the script in AWS itself. We've deliberately decided to deviate from the standard `aws` CLI behaviour here so that people can't unexpectedly run commands using credentials in the default profile if they forget the …
=> Use default AWS credentials if no profile is set

README.md
This PR adds some more perms to the readme, as it turns out they are needed to avoid a future timing out after 25 seconds.
=> correct the permissions needed in the readme

build.sbt, src/test/scala/com/gu/ssm/LogicTest.scala, src/test/scala/com/gu/ssm/MainTest.scala, src/test/scala/com/gu/ssm/SSHTest.scala, src/test/scala/com/gu/ssm/UITest.scala, src/test/scala/com/gu/ssm/utils/attempt/AttemptTest.scala, src/test/scala/com/gu/ssm/utils/attempt/AttemptValues.scala
Bumps dependencies to latest minor version available.
Note:
- It looks like `scalatest` v3.2.9 has a different package layout, so imports across the tests have also been updated.
- `scopt` has a v4 release. As this is a major change it's likely to include breaking changes and should be upgraded separately.
=> chore: Bump dependencies to latest minor version available

.github/workflows/compile-test.yml, build.sbt, project/build.properties, src/test/scala/com/gu/ssm/LogicTest.scala, src/test/scala/com/gu/ssm/MainTest.scala, src/test/scala/com/gu/ssm/SSHTest.scala, src/test/scala/com/gu/ssm/UITest.scala, src/test/scala/com/gu/ssm/utils/attempt/AttemptTest.scala, src/test/scala/com/gu/ssm/utils/attempt/AttemptValues.scala
This is to remediate CVE-2021-44228.
Note: CI has been updated to use the action provided by GitHub as the previous one [wasn't working](https://github.com/guardian/ssm-scala/runs/4547658581?check_suite_focus=true):
```log
Step 8/11 : RUN   curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb &&   dpkg -i sbt-$SBT_VERSION.deb &&   rm sbt-$SBT_VERSION.deb
---> Running in 0ff3fe5c20c3
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   166  100   166    0     0    410      0 --:--:-- --:--:-- --:--:--   410
dpkg-deb: error: 'sbt-1.3.0.deb' is not a debian format archive
dpkg: error processing archive …
```
=> chore: Bump sbt to 1.5.7

build.sbt, project/plugins.sbt, src/main/scala/com/gu/ssm/Interactive.scala
This change batches the updates in:
- https://github.com/guardian/ssm-scala/pull/161
- https://github.com/guardian/ssm-scala/pull/158
- https://github.com/guardian/ssm-scala/pull/157
- https://github.com/guardian/ssm-scala/pull/156
- https://github.com/guardian/ssm-scala/pull/155
- https://github.com/guardian/ssm-scala/pull/154
- https://github.com/guardian/ssm-scala/pull/142
This updates all recommended libraries and removes some identified vulnerabilities. 
**Note:**  We should set up batched Scala steward updates for this repository.
=> Batch Scala Steward updates

README.md, build.sbt, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/IO.scala, src/main/scala/com/gu/ssm/Logic.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/aws/RDS.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/LogicTest.scala, src/test/scala/com/gu/ssm/SSHTest.scala
Adds two options to enable SSH tunnelling. They're mutually exclusive.
The first, `--tunnel localPort:hostname:remotePort`, allows the user to specify an arbitrary hostname and remote port.
The second, `--rds-tunnel localPort:list,of,tags`, allows the user to specify a local port, and a list of tags. SSM looks up an RDS instance via the tags, failing if there are 0 or many instances.
Across our estate, we have many scripts that accomplish this in a few different ways – here are [a few examples,](https://github.com/search?q=org%3Aguardian+path%3Assh-tunnel&type=code) and I suspect there are more. These commands aim to replace most of them with a one-liner that can be included in project README files and used directly.
There are a few decisions here that gave me pause. One concerns the …
=> Add commands for SSH tunnelling

README.md, generate-executable-prefix, src/main/scala/com/gu/ssm/ArgumentParser.scala, src/main/scala/com/gu/ssm/Main.scala, src/main/scala/com/gu/ssm/SSH.scala, src/main/scala/com/gu/ssm/models.scala, src/test/scala/com/gu/ssm/SSHTest.scala
This PR modifies ssm-scala so that you no longer need to pass `-x` or `--execute` in order to get it to execute the ssh command. 
In 7 years of using SSM, I don't think I have ever wanted to run a command without `-x`. The only use case has been for scripts which have made use of `--raw` to build a more complex ssh command. With that in mind, I have modified the `--raw` setting so that it now disables execution.
This PR introduces a new 'dryrun' command line option as a way of getting the old behaviour back (printing out the ssh command rather than executing). 
As this affects the default behaviour of SSM I this will need to be at least a minor version bump and I'll send out some comms as well after releasing.
Two characters less typing every time anyone uses SSM. Only 2 characters! So …
=> Make -x (execute) the default behaviour

build.sbt
For a new release of ssm-scala, containing this change https://github.com/guardian/ssm-scala/pull/375
My motivation for a major version bump is that technically the changes in #375 are not backwards compatible - whilst anyone using `--raw` or `-x` will not be affected, anyone relying on the output with neither of those flags set will now get a new result.
=> Bump version number to 3.4.0

build.sbt, src/main/scala/com/gu/ssm/models.scala, src/main/scala/com/gu/ssm/utils/attempt/Failure.scala
This PR upgrades ssm-scala onto to scala 3. 
This is my first scala 3 upgrade so I'm by no means an expert, I simply ran the 4 commands outline in the migration plugin https://github.com/scalacenter/scala3-migrate and there were very few changes.
I've tested this locally using both sbt console and the generated executable from `./generate-executable.sh`
I'm not sure - maybe some performance improvements.
=> Migrate to scala 3

build.sbt, generate-executable.sh
Bumps the version number of ssm-scala in order to release https://github.com/guardian/ssm-scala/pull/378
=> Bump version to v3.5.0

build.sbt
Adds the scala option to target a specific version of the jvm (v11).
=> Feat: target a specific java version

.github/dependabot.yml
switches from weekly GHA updates to monthly
The project is not active enough for weekly dependency bumps to be useful. Reduces workload on a small team. Dependabot has a different process for raising PRs in response to vulnerability disclosures, so this will not affect our response time to new vulnerabilities.
=> dependabot.yml to bump monthly

.github/workflows/compile-test.yml
sbt is no longer available on Github's test runners, so we need to explicitly install it.
This will mean CI works again!
=> Install sbt in CI

build.sbt, generate-executable.sh
Since this script includes the hard-coded Scala version, it is essential that this is kept in sync with the Scala version defined in the build.sbt file. We might consider automating this coupling away, but for now I've fixed the reference and added a comment to the build.sbt file so it is less likely these versions drift apart in the future.
The generate-executable script is part of the release process, so this ensures that the program can be released.
If this becomes tedious in the future then we can automatically extract the scala version from the build.sbt file, or by inspecting the filesystem structure.
=> Update the Scala version in the generate executable script

.github/workflows/compile-test.yml, .github/workflows/sbt-dependency-graph.yaml, .tool-versions
Replaces #452 #453 #454
We now use our own setup-scala workflow, instead of having to set up Java and sbt separately. This requires that we specify a java version in our `.tool-versions` file.
Note: We're only specifying the major Java version so that we aren't providing irrelevant minor and patch versions that will drift out of date over time. This is not supported by `asdf`, but switching to [mise](https://mise.jdx.dev/) will work as a drop-in replacement.
This will reduce the number of PRs that land on this project in the future.
We also bump the actions/checkout version to consolidate the GHA changes.
=> Simplify GitHub Actions workflows

build.sbt, generate-executable.sh
For future viewers, this is following the [instructions in Readme](https://github.com/guardian/ssm-scala?tab=readme-ov-file#release-a-new-version).
=> Chore: Prepare for release of v3.8.0

generate-executable.sh
Just a minor typo but still nice to fix
=> Fix typo in generate-executable
